services:
  - type: web
    name: battle-guess
    runtime: static
    buildCommand: rm -rf node_modules package-lock.json && NODE_OPTIONS="--max-old-space-size=2048" npm install --no-optional && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: NPM_CONFIG_OPTIONAL
        value: "false"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 