services:
  - type: web
    name: battle-guess
    runtime: static
    buildCommand: ./build.sh
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_CONFIG_OPTIONAL
        value: "false"
      - key: SKIP_PNPM
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 