services:
  - type: web
    name: battle-guess
    runtime: static
    buildCommand: pnpm install && pnpm build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 